### ISSUE TITLE
nvrtc: error: failed to open libnvrtc-builtins.so.11.6

### ISSUE THREAD

**Issue by AlexMorgand** [lfranke/TRIPS#13]
Anybody experienced a similar error?

```
nvrtc: error: failed to open libnvrtc-builtins.so.11.6
```
It's compiling fine following the conda instructions on Ubuntu 22

Basically trying to run
```
./build/bin/train --config configs/train_normalnet.ini --TrainParams.scene_names playground_test --TrainParams.name
```

Thanks in advance, can't wait to test it!

**Comment by lfranke** [comment]
Hi,
you probably need to make these calls first:
```
conda activate trips
export CONDA=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA/lib
```
for the runtime to find the conda-installed cuda libraries and then run the train binary
