### ISSUE TITLE
Windows installatoin issues & Nvidia Cuda NvToolsExt

### ISSUE THREAD

**Issue by dm-de** [lfranke/TRIPS#15]
I found 3 issues

**1:**
`git submodule update --init --recursive --jobs 0`
does not work, but this does:
`git submodule update --init --recursive --jobs 1`

By the way, I was unable to clone with:
`git clone git@github.com:lfranke/TRIPS.git`
Instead, I used this:
`git clone https://github.com/lfranke/TRIPS.git`

---

**2:**
`cmake -Bbuild -DCMAKE_CUDA_COMPILER="$ENV:CUDA_PATH\bin\nvcc.exe" -DCMAKE_PREFIX_PATH=".\External\libtorch" -DCONDA_P_PATH="$ENV:CONDA_PREFIX" -DCUDA_P_PATH="$ENV:CUDA_PATH" -DCMAKE_BUILD_TYPE=RelWithDebInfo .`

I get this error:

```
CMake Error at External/saiga/cmake/Dependencies_cuda.cmake:21 (enable_language):
  The CMAKE_CUDA_COMPILER:
    $ENV:CUDA_PATH\bin\nvcc.exe
  is not a full path and was not found in the PATH.
```
  
Then I replaced this line with:

`cmake -Bbuild -DCMAKE_CUDA_COMPILER="%CUDA_PATH%\bin\nvcc.exe" -DCMAKE_PREFIX_PATH=".\External\libtorch" -DCONDA_P_PATH="%CONDA_PREFIX%" -DCUDA_P_PATH="%CUDA_PATH%" -DCMAKE_BUILD_TYPE=RelWithDebInfo .`

---

**3:**
It works much better, but now, I have this error:

```
CMake Error in src/lib/CMakeLists.txt:
  Imported target "torch" includes non-existent path
    "C:/Program Files/NVIDIA Corporation/NvToolsExt/include"
  in its INTERFACE_INCLUDE_DIRECTORIES.
```
  
My Cuda 11.8 installation has no C:/Program Files/NVIDIA Corporation/NvToolsExt

I found some files here:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\nvtx3
nvToolsExt.h
etc.

I'm not sure what is wrong here

I installed Cuda 11.8 selecting this:
Development/*
Runtime/Libraries/*
Visual Studio Integration

![grafik](https://github.com/lfranke/TRIPS/assets/48416452/170f636b-8804-4eb4-88c9-e2997d405c2a)

**Comment by dm-de** [comment]
It seems that this zip is for Cuda 11.6 - not 11.8
right?

https://download.pytorch.org/libtorch/cu116/libtorch-win-shared-with-deps-1.13.1%2Bcu116.zip

**Comment by lfranke** [comment]
Ah perfect! I will add this to the README!
