### ISSUE TITLE
Crash when switching to Neural view (F2) on Windows

### ISSUE THREAD

**Issue by AlessioRegal** [lfranke/TRIPS#18]
Hello,

When I switch to the Neural view, the viewer crashes with the following log:

`loading shader shader//point_render.glsl
AABB: [-51.5333 -17.594 -47.2529 ] [47.4672 6.87171 50.7299 ]
[Renderer] Target resized to 3102x1161
[DeferredRenderer] Resize 3102x1161
Assertion 'pipeline' failed!
  File: D:\NERF\TRIPS\src\lib\opengl\RealTimeRenderer.cpp:881
  Function: class at::Tensor __cdecl RealTimeRenderer::Render(struct ImageInfo,class Eigen::Matrix<float,3,1,0>,int)`
  
  I tested this with the following scenes: "tt_m60", "tt_horse" and "tt_train".
  The Model view (F1) works correctly insteada.

**Comment by lfranke** [comment]
Hi,
can you check if you downloaded and extracted the checkpoints to `experiments/`?
If there are no checkpoints, the viewer will start in Model view and fail if switched to the other views.

**Comment by AlessioRegal** [comment]
that was the issue, thanks!
