### ISSUE TITLE
fatal: could not read from the remote repository

### ISSUE THREAD

**Issue by Tekn1ck** [lfranke/TRIPS#19]
Hi, I have this issue, probably because I was not sure what to do with the yes/no/fingerprint option after trying to clone the git repository. What should I do to fix this so it installs?

(base) C:\Users\Me>git clone git@github.com:lfranke/TRIPS.git
Cloning into 'TRIPS'...
The authenticity of host 'github.com (20.248.137.48)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? fingerprint
Please type 'yes', 'no' or the fingerprint: SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by hariharan1412** [comment]
git clone https://github.com/lfranke/TRIPS.git

**Comment by Tekn1ck** [comment]
perfect - that worked!

**Comment by hariharan1412** [comment]
Kindly please close the issue
