### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by pknmax** [lfranke/TRIPS#20]
how to compile TRIPS with other compiler like 
```
main⚡ » gcc --version       
gcc (conda-forge gcc 12.3.0-5) 12.3.0
```

**Comment by hadillivvy** [comment]
Hi @pknmax 

I'm not one of the authors but I had gcc 11 and g++ 11 installed on my machine when I did the installation and I changed all references to gcc-9 and g++-9 to gcc-11 and g++-11 and it worked fine for me! For example:

```
export CC=gcc-11
export CXX=g++-11
export CUDAHOSTCXX=g++-11
unset CUDA_HOME
```

Maybe you can try that?

**Comment by lfranke** [comment]
Thanks for testing @hadillivvy!
As far as I know, gcc-11 should work fine. I think gcc-12 is not supported by CUDA 11.8.
