### ISSUE TITLE
Export .ply (structures only)

### ISSUE THREAD

**Issue by hariharan1412** [lfranke/TRIPS#33]
Hello @lfranke  I'm really amazed by your work and want to thank you first.

And I have a doubt,

> Hi, this is currently a bit difficult, as our point colors/descriptors have no real RGB meaning without the neural network convolutions afterwards.

Since you have mentioned it has "no real RGB" value, is it possible to export a .PLY file with only Pointclould Structures not colors?

**Comment by lfranke** [comment]
Hi, yes this is possible. when you compile with `-DMINIMAL_GUI=ON`, on the bottom left there should be an `save points ply` button. It however will only export the positions and original rgb colors, of which only the point positions will be optimized for TRIPS
