### ISSUE TITLE
Is it possible to fix this if my graphics card only supports sm_60?

### ISSUE THREAD

**Issue by Disa-Kizonda** [lfranke/TRIPS#5]
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include\cuda\std/barrier(11): 

fatal error C1189: #error:  "CUDA synchronization primitives are only supported for sm_70 and up." [D:\vann\TRIPS\build\src\lib\NeuralPoints.vcxproj]

RenderForward.cu

**Comment by lfranke** [comment]
Unfortunately no, sorry! TRIPS requires these synchronization features from sm_70
