### ISSUE TITLE
how to make installation without conda envs?

### ISSUE THREAD

**Issue by datasciritwik** [lfranke/TRIPS#9]
Hi,

I have an Ubuntu system, and some of my other projects may be hampered if I install Conda. So can we make the installation without conda?

Thank u.

**Comment by lfranke** [comment]
Hi,
yes that should work as we only use conda as our package manager.
Maybe if you install cuda11.8, cudnn 8.9.5, mkl and cmake 3.26 yourself. You probably also need to remove the Ubuntu tensorboard part from the `TRIPS/CMakeLists.txt` file (line 31 to 36).

However, I'm not able to try this currently, sorry!
